import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const circular = localFont({
  src: [
    {
      path: "./fonts/CircularStd-Light.otf",
      weight: "300", // Adjusted to a more appropriate weight for "Light"
      style: "normal",
    },
    {
      path: "./fonts/CircularStd-Book.otf",
      weight: "400", // Standard weight for "Book"
      style: "normal",
    },
    {
      path: "./fonts/CircularStd-Medium.otf",
      weight: "500", // Medium weight
      style: "normal",
    },
    {
      path: "./fonts/CircularStd-Bold.otf",
      weight: "700", // Bold
      style: "normal",
    },
    {
      path: "./fonts/CircularStd-Black.otf",
      weight: "900", // Black (heaviest weight)
      style: "normal",
    },
    {
      path: "./fonts/CircularStd-LightItalic.otf",
      weight: "300", // Italic version of "Light"
      style: "italic",
    },
  ],
  variable: "--font-geist-sans",
  display: "swap", // Optional, but helps with performance
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${circular.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
